In [1]:
import numpy as np

imgs=[np.random.randint(5, size=(2,2, 3)),np.random.randint(5, size=(2, 2,3))]
imgs

[array([[[1, 4, 3],
         [3, 4, 0]],
 
        [[1, 1, 4],
         [2, 3, 3]]]),
 array([[[2, 1, 0],
         [2, 3, 1]],
 
        [[0, 1, 4],
         [2, 4, 2]]])]

In [2]:
imgs[0]

array([[[1, 4, 3],
        [3, 4, 0]],

       [[1, 1, 4],
        [2, 3, 3]]])

In [3]:
imgs[1]

array([[[2, 1, 0],
        [2, 3, 1]],

       [[0, 1, 4],
        [2, 4, 2]]])

In [6]:
np.sum([imgs[0]], axis=0)

array([[[1, 4, 3],
        [3, 4, 0]],

       [[1, 1, 4],
        [2, 3, 3]]])

In [5]:
!python3 PREPROCESING/segmentation.py

/usr/local/bin/python3: can't open file 'PREPROCESING/segmentation.py': [Errno 2] No such file or directory
